name: "Optim Guard"
description: "Blocks pull requests with unoptimised images"
author: "Chris Rutkowski"
inputs:
  ignore_file:
    description: "Path to the ignore file"
    required: true
    default: "./optim_guard.ignore"
  process_pdfs:
    description: "Converts PDFs to SVGs and optimises them"
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install optimization tools
      run: |
        sudo apt-get update
        sudo apt-get install -y pngquant jpegoptim webp gifsicle pdf2svg
        npm install -g svgo
      shell: bash

    - name: Get changed files
      if: ${{ github.event_name == 'pull_request' }}
      id: changed-files
      uses: tj-actions/changed-files@v45
      with:
        json: true
        write_output_files: true
        safe_output: false

    - name: Get all files
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        mkdir -p .github/outputs/
        find . -type f | sed 's|^\./||' | jq -R . | jq -s . > .github/outputs/all_repo_files.json
      shell: bash

    - name: Run Optim Guard
      run: |
        python3 ${GITHUB_ACTION_PATH}/optim_guard.py ${{ inputs.ignore_file }} .github/outputs/modified_files.json .github/outputs/added_files.json .github/outputs/all_repo_files.json --process_pdfs=${{ inputs.process_pdfs }}
      shell: bash

    - name: Upload
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: optim_guard_result
        path: optim_guard_result
        retention-days: 1
